### ISSUE TITLE
Question Regarding PC Specs

### ISSUE THREAD

**Issue by SamuelBanya** [ZFEbHVUE/Batocera-CRT-Script#236]
Hey there, I noticed you listed to use AMD cards for a build like this.

However, what is the max specs that are recommended for something like this?

Debating using a PC I have laying around for this which has an i7 from 2017 era, and 16 gigs ram but a Nvidia card (1060 gt I think).

Should I get a compatible AMD card and some kind of adapter to convert the output to composite for an old Toshiba 32 inch TV I have?

Curious for your thoughts on this as I have used Batocera in the past, and it has kicked ass on things like the Steam Deck etc.

**Comment by ZFEbHVUE** [comment]
Hi Samuel,

For me the computer is very good but I don't think it is a good idea to use GTX 1060.  I never test it but I have an GTX 1050TI (Pascal architecture). I can say it works but with HDMI so you have a restriction about dotclock min equals to 25.  I have some HDMI-VGA aable to get 6. But anyway, for me Pascal isn't the best for Nvidia. Turning is awfull. To get full 15KHz, better to use Maxell.  Otherwise Amd is the best choose to get 15KHz. An R9 380x is one of the best.

Stéphane.
