### ISSUE TITLE
Excuse me, how can I use this script to using r9 380x？

### ISSUE THREAD

**Issue by mingkosan** [ZFEbHVUE/Batocera-CRT-Script#243]
No matter how much you try to change the settings, they won't succeed

**Comment by Redemp** [comment]
Well you obviously did something wrong since I have several R9 380 cards and no issues.
You need to apply the script to a fresh v40 **Official Image** 
https://batocera.org/download

We don't support 3rd party images.

Follow the instructions to the letter from here
https://github.com/ZFEbHVUE/Batocera-CRT-Script/blob/main/HowTo_Wired_Or_Wireless_Connection.md

If you need more support then join the official Discord channel and head over to the **# CRT** channel.
https://discord.com/invite/JXhfRTr

**Comment by Redemp** [comment]
Closing this as issue has been explained
